### ISSUE TITLE
Wrong Context for Multiple Dynamic Segments

### ISSUE THREAD

**Issue by jiahanwang** [mike-north/ember-perf#101]
When there are multiple dynamic segments in the route such as `/posts/:post_id/comments/:comment_id`,

ember-perf would result in a error: 
`You didn't provide enough string/numeric parameters to satisfy all of the dynamic segments`

The root cause could be: ember perf only take first element in the context array, and thus not all the  parameters are passed to ember router.
https://github.com/mike-north/ember-perf/blob/master/addon/services/ember-perf.js#L66

**Comment by kiwiupover** [comment]
closed by #136
