### ISSUE TITLE
Support for IE9

### ISSUE THREAD

**Issue by gzurbach** [mike-north/ember-perf#17]
We just added ember-perf in our app but it is not working in IE9.

In `performance-now.js` (https://github.com/mike-north/ember-perf/blob/master/addon/utils/performance-now.js) the following code crashes:
```
if ('performance' in window) {
  return window.performance.now();
} else {
  return new Date().valueOf();
}
```

It seems like `window.performance` is present in IE9, but `window.performance.now` isn't:
 - window.performance: https://developer.mozilla.org/en-US/docs/Web/API/Performance#Browser_compatibility
 - window.performance.now: https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#Browser_compatibility

Will send a PR your way soon if that's okay?

**Comment by mike-north** [comment]
Resolved by #23, check out `v0.1.0`, and give @kiwiupover a high-five for his great work
